language: java
install:
 - unzip -q bundle/sencha-cmd-3.1.2.342.zip -d bundle/sencha-cmd
 - git clone git://github.com/burnnat/vexflow.git bundle/vexflow
script:
 - ant -Dcmd.dir=$TRAVIS_BUILD_DIR/bundle/sencha-cmd -Dvexflow.dir=$TRAVIS_BUILD_DIR/bundle/vexflow
