language: node_js
node_js:
- "0.10"
services:
- mongodb
before_install:
- ./setup.sh travis
script:
- ant -Dcmd.dir=$TRAVIS_BUILD_DIR/bundle/Sencha/Cmd/4.0.0.230 -Dvexflow.dir=$TRAVIS_BUILD_DIR/bundle/vexflow
- npm test
env:
  global:
  - secure: |-
      m1X9g9pMtu+ZmN8q17RNErGyjkvGFTz8F/NCFd0Qzknn2EL8t9Vr6Zc5IQmK
      OyXPu33yLeUc9jphaqneZfUy34IGPgkUXG2xO1LX1lfbWe14PsPnCG9709Jo
      BKGzrsozTvinP2Vhxf1cKXPugaMWHZxah6U1n5zqslqV6Gyvfa4=
  - secure: |-
      Z1ohHBHcdg/KQj4FTBHc4iCi0giZOfRjykcQ1xK5wJEfAX/OJf8tuGEQdCSo
      5mfcudSox80u/ZkyfWShfJdqtvhqBe5a0OxgBg+D99XduyvRpLBEQH6cGF5Q
      asr3A/7r064YKbQkAg2fTbXarvDqvOhVmryaT1yYkfcDXtK2uBE=
  - secure: |-
      dR2yAug3+7jZ7b9jWdWSq6pjtW/1OvdL1BWaiXipf7qtQmMbRofmrbTMEQFz
      mlkkwL1BHOJMsytl9Fpoje8xjS2OnBldzapokme8y9MokZ+S16DFJGWF37bL
      jDVmn86pyvlASgOVqUaORC6T3tRGcaoUcauUyYC7NZINQspLiDU=
  - secure: |-
      Q4L5C3UeWiieSOf3TTCSuu7BVqQN0a2wI3o3+FHA1fwwHLHVclp+lSU9bZnb
      3Js0dVWcc+X1asjg+BmGDBATlzFkSq5vjQuaL2cQ2gI2WMyPI7I/DeVYKe1p
      FT9NRjxG5gtGvllspnSJnmdI19bil7XrDmdesrpEsZBfVCC+DsU=
  - secure: |-
      U94AUqqvbKFrJ4inzRjwZRWNdOdovThTFH1YySneZTPJBdAGB6IyJPPf+7h0
      edHufUehJlHfIZv4DnNAanFo+diMFhEvYkDTj7xXWcxO6WNOkG27sLoGZJ+g
      V6GsY2TIsE6vqAxnEsAtlKBGmgNsT/8EzWkb3RVAlcO1pJUxQB8=
  - secure: |-
      WideSBxshNZtLutr75MH4eCHKcM4YHqkUrFOOKAMtWly2f29AxEpanfdi6Uv
      UyZt8NUaY3Z5XkeA6AEwiQ764ZwkAHNPq2KFzzymS2+fUbBA0nJ5PF+yXM7O
      hJHirsa2tJ9Fm8kv/MDR4ECK9zhOnKODzLQJrRJn0z6ZhPm2vPs=